# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

# osx_image: xcode8.0
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
  - brew update && brew upgrade xctool
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/SwiftBarcodeReader.xcworkspace -scheme SwiftBarcodeReader-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
